export const CV_meta_data ={
    title: "The Curriculum Vitae of Brett Gamble",
    description: "Detailed work history, education and skill set of Brett Gamble",
    generator: 'Next.js',
    applicationName: 'Brett Gamble - Portfolio',
    referrer: 'origin-when-cross-origin',
    keywords: ['Brett K Gamble', 'Brett Gamble', 'Curriculum Vitae', 'Resume', 'Portfolio', 'Brett Gamble Edmonton',
    'Brett Gamble Heathcote High School'],
    authors: [{ name: 'Brett Gamble', url: 'https://brettkgamble.com' }],
    colorScheme: 'dark',
    creator: 'Brett Gamble',
    publisher: 'Brett Gamble',
    alternates: {},
    formatDetection: {
        email: false,
        address: false,
        telephone: false,
    },
    openGraph: {
        title: "The Curriculum Vitae of Brett Gamble",
        description: "Detailed work history, education and skill set of Brett Gamble",
        url: 'https://www.brettkgamble.com',
        siteName: 'Brett Gamble - Portfolio',
        type: 'website',
        publishedTime: '2023-01-01T00:00:00.000Z',
        authors: ['Brett Gamble'],
        locale: 'en-US',
        // images: [
        //   {
        //     url: 'https://nextjs.org/og.png',
        //     width: 800,
        //     height: 600,
        //   },
        //   {
        //     url: 'https://nextjs.org/og-alt.png',
        //     width: 1800,
        //     height: 1600,
        //     alt: 'My custom alt',
        //   },
        // ],

  },
    robots: {
    index: false,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: false,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}